const productConst = [{
    "job_id": "638f1017cf5870603307b71d",
    "status": "finished",
    "results": [
        {
            "updated_at": "2022-12-06T09:49:37.442Z",
            "query": {
                "max_age": 1200,
                "max_pages": 1,
                "value": "iphone 11",
                "key": "term",
                "country": "se",
                "topic": "search",
                "source": "google"
            },
            "content": {
                "offers": [
                    {
                        "review_count": "",
                        "review_rating": "",
                        "seller_url": "https://www.alloallo.com/se/refurbished-iphone/iphone-11/64-gb/",
                        "seller": "alloallo.com",
                        "condition": "Restaurerad",
                        "shipping": 0,
                        "currency": "SEK",
                        "price": 3459.9,
                        "url": "https://www.alloallo.com/se/refurbished-iphone/iphone-11/64-gb/",
                        "name": "iPhone 11 64GB"
                    },
                    {
                        "review_count": "",
                        "review_rating": "",
                        "seller_url": "https://smartspares.se/product/iphone-11-64gb-begagnad/?attribute_pa_farg=gron",
                        "seller": "Smartspares.se",
                        "condition": "",
                        "shipping": 0,
                        "currency": "SEK",
                        "price": 3500,
                        "url": "https://smartspares.se/product/iphone-11-64gb-begagnad/?attribute_pa_farg=gron",
                        "name": "iPhone 11 64GB - Begagnad"
                    },
                    {
                        "review_count": 7,
                        "review_rating": 4.8,
                        "seller_url": "https://www.returhuset.se/iphone-11.html",
                        "seller": "Returhuset SE",
                        "condition": "Restaurerad",
                        "shipping": 0,
                        "currency": "SEK",
                        "price": 4690,
                        "url": "https://www.returhuset.se/iphone-11.html",
                        "name": "iPhone 11"
                    },
                    {
                        "review_count": "",
                        "review_rating": "",
                        "seller_url": "https://www.netonnet.se/art/mobil-smartwatch/mobiltelefoner/iphone/apple-iphone-11-64gb-black-2020/1015698.9044/?srsltid=AYJSbAftMg-YfhkiIa066ihPRvJJ0WpLxNHdw1WrJ3LSevDJXNsQrJpu10o",
                        "seller": "NetOnNet",
                        "condition": "",
                        "shipping": 0,
                        "currency": "SEK",
                        "price": 5990,
                        "url": "https://www.netonnet.se/art/mobil-smartwatch/mobiltelefoner/iphone/apple-iphone-11-64gb-black-2020/1015698.9044/?srsltid=AYJSbAftMg-YfhkiIa066ihPRvJJ0WpLxNHdw1WrJ3LSevDJXNsQrJpu10o",
                        "name": "Apple iPhone 11 64GB Black (2020) - Färgstark. Kraftfull. Ett absolut måste. - Mobiltelefoner - iPhone"
                    },
                    {
                        "review_count": "",
                        "review_rating": "",
                        "seller_url": "https://www.alina.se/Produkt.aspx?site=Test&T2=IP11_BACK_GN",
                        "seller": "Alina.se",
                        "condition": "",
                        "shipping": 49,
                        "currency": "SEK",
                        "price": 1999,
                        "url": "https://www.alina.se/Produkt.aspx?site=Test&T2=IP11_BACK_GN",
                        "name": "Apple iPhone 11 - Baksidebyte Org - Green"
                    },
                    {
                        "review_count": "",
                        "review_rating": "",
                        "seller_url": "https://cdon.se/hemelektronik/iphone-11-64gb-svart-grade-a-p71775828",
                        "seller": "cdon.se",
                        "condition": "Begagnad",
                        "shipping": 79,
                        "currency": "SEK",
                        "price": 4799,
                        "url": "https://cdon.se/hemelektronik/iphone-11-64gb-svart-grade-a-p71775828",
                        "name": "iPhone 11 64GB Svart Grade A - Mobiltelefoner"
                    },
                    {
                        "review_count": "",
                        "review_rating": "",
                        "seller_url": "https://www.refurbly.se/produkt/iphone-11-pro?color=silver&capacity=64GB&grade=C&abonnemang=true&utm_source=Google%20Shopping&utm_campaign=Refurbly%20Google&utm_medium=cpc",
                        "seller": "Refurbly",
                        "condition": "Restaurerad",
                        "shipping": 0,
                        "currency": "SEK",
                        "price": 239,
                        "url": "https://www.refurbly.se/produkt/iphone-11-pro?color=silver&capacity=64GB&grade=C&abonnemang=true&utm_source=Google%20Shopping&utm_campaign=Refurbly%20Google&utm_medium=cpc",
                        "name": "Begagnad iPhone 11 Pro 64GB Silver - Abonnemang utan bindningstid"
                    },
                    {
                        "review_count": "",
                        "review_rating": "",
                        "seller_url": "https://www.refurbed.se/p/iphone-11/4782c/?co=se&utm_cluster=gradeC&utm_content=iphone-11-4782c&utm_group=iphone-11",
                        "seller": "refurbed.se",
                        "condition": "Restaurerad",
                        "shipping": 0,
                        "currency": "SEK",
                        "price": 4604.99,
                        "url": "https://www.refurbed.se/p/iphone-11/4782c/?co=se&utm_cluster=gradeC&utm_content=iphone-11-4782c&utm_group=iphone-11",
                        "name": "Bra: iPhone 11 | 64 GB | vit"
                    },
                    {
                        "review_count": 44622,
                        "review_rating": 4.6,
                        "seller_url": "https://www.certideal.se/iphone-11-rekonditionerad/iphone-11-64-gb-lila-4953?srsltid=AYJSbAcoCfk0kRC_6GLgSX_8W_sw9XvJFCxmuBGzFCZMXfeZgxTnOtHunZ8",
                        "seller": "CertiDeal.se",
                        "condition": "Restaurerad",
                        "shipping": 25,
                        "currency": "SEK",
                        "price": 4062,
                        "url": "https://www.google.se/shopping/product/r/SE/18058987589289720762?prds=oid:17352680021027758144,eto:17352680021027758144_0,epd:17352680021027758144,prmr:1,rsk:PC_8023149794696260886&q=iphone+11&rss=ChZQQ184MDIzMTQ5Nzk0Njk2MjYwODg2&hl=sv&gl=se",
                        "name": "Apple Iphone 11 - 4G Smartphone - Dual-Sim / Internal Memory 64 Gb - Lcd-Skärm - 6.1\" - 1792 X 828 Pixlar - 2 Bakre Kameror 12 Mp, 12 Mp - Front Came"
                    },
                    {
                        "review_count": "",
                        "review_rating": "",
                        "seller_url": "https://swappie.com/se/iphone/iphone-11/iphone-11-64gb-rod-3/",
                        "seller": "Swappie",
                        "condition": "Restaurerad",
                        "shipping": 75,
                        "currency": "SEK",
                        "price": 4009,
                        "url": "https://swappie.com/se/iphone/iphone-11/iphone-11-64gb-rod-3/",
                        "name": "Apple iPhone 11 64GB Röd Apple"
                    },
                    {
                        "review_count": 10146,
                        "review_rating": 4.7,
                        "seller_url": "https://shop.halebop.se/mobiltelefoner/apple/mycket-bra-skick-iphone-11-pro-max-64gb-guld/123654",
                        "seller": "Halebop",
                        "condition": "Begagnad",
                        "shipping": 0,
                        "currency": "SEK",
                        "price": 389,
                        "url": "https://www.google.se/shopping/product/r/SE/2071002033948015895?prds=oid:13690079452020836177,eto:13690079452020836177_0,epd:13690079452020836177,prmr:1,rsk:PC_251453032899230491&q=iphone+11&rss=ChVQQ18yNTE0NTMwMzI4OTkyMzA0OTE%3D&hl=sv&gl=se",
                        "name": "Iphone 11 Pro Max 64gb"
                    },
                    {
                        "review_count": "",
                        "review_rating": "",
                        "seller_url": "https://www.teknikmagasinet.se/produkter/mobilt/mobiltelefoner/begagnade-mobiltelefoner/iphone-11-64gb-svart-okej-skick",
                        "seller": "Teknikmagasinet",
                        "condition": "Begagnad",
                        "shipping": 0,
                        "currency": "SEK",
                        "price": 4699,
                        "url": "https://www.teknikmagasinet.se/produkter/mobilt/mobiltelefoner/begagnade-mobiltelefoner/iphone-11-64gb-svart-okej-skick",
                        "name": "iPhone 11 64gb Svart Okej skick"
                    },
                    {
                        "review_count": "",
                        "review_rating": "",
                        "seller_url": "https://www.telenor.se/handla/mobiler/apple/iphone-11/#p%3Dts%26cty%3D64%26clr%3D%23f9f6ef%26s%3D7545",
                        "seller": "Telenor",
                        "condition": "",
                        "shipping": 0,
                        "currency": "SEK",
                        "price": "290,00 kr nu+290,00 kr i 24 månader",
                        "url": "https://www.telenor.se/handla/mobiler/apple/iphone-11/#p%3Dts%26cty%3D64%26clr%3D%23f9f6ef%26s%3D7545",
                        "name": "iPhone 11 64 GB Vit"
                    },
                    {
                        "review_count": 44622,
                        "review_rating": 4.6,
                        "seller_url": "https://www.certideal.se/iphone-11-rekonditionerad/iphone-11-128-gb-vit-4963?srsltid=AYJSbAegJnAJYERJYfr-siNdWSXbRNMIy8U3soj14UMFoz2UtiS9PM7_ojU",
                        "seller": "CertiDeal.se",
                        "condition": "Restaurerad",
                        "shipping": 25,
                        "currency": "SEK",
                        "price": 4607,
                        "url": "https://www.google.se/shopping/product/r/SE/14865635438453690148?prds=oid:6466222091738812479,eto:6466222091738812479_0,epd:6466222091738812479,prmr:1,rsk:PC_8023149794696260886&q=iphone+11&rss=ChZQQ184MDIzMTQ5Nzk0Njk2MjYwODg2&hl=sv&gl=se",
                        "name": "Apple Iphone 11 (128gb) Vit"
                    },
                    {
                        "review_count": "",
                        "review_rating": "",
                        "seller_url": "https://primemobile.se/iphone-11-pro-max-skarmbyte-39.html",
                        "seller": "primemobile.se",
                        "condition": "",
                        "shipping": 99,
                        "currency": "SEK",
                        "price": 1000,
                        "url": "https://primemobile.se/iphone-11-pro-max-skarmbyte-39.html",
                        "name": "iPhone 11 Byta Sidoknappar"
                    },
                    {
                        "review_count": "",
                        "review_rating": "",
                        "seller_url": "https://telefy.se/produkt/begagnad-mobil/iphone-11-64gb-vit-klass-c/",
                        "seller": "Telefy.se",
                        "condition": "",
                        "shipping": 79,
                        "currency": "SEK",
                        "price": 4199,
                        "url": "https://telefy.se/produkt/begagnad-mobil/iphone-11-64gb-vit-klass-c/",
                        "name": "iPhone 11 - 64GB - Vit - Klass C"
                    },
                    {
                        "review_count": "",
                        "review_rating": "",
                        "seller_url": "https://fyndiq.se/produkt/iphone-11-128gb-1d8b4a87225f4ba3/?srsltid=AYJSbAe0x8mW-79lYFxjOYgV6p4mcIArollN2co5sdZr-FFUE8bksfMIRzk",
                        "seller": "Fyndiq.se",
                        "condition": "Restaurerad",
                        "shipping": 0,
                        "currency": "SEK",
                        "price": 5299,
                        "url": "https://fyndiq.se/produkt/iphone-11-128gb-1d8b4a87225f4ba3/?srsltid=AYJSbAe0x8mW-79lYFxjOYgV6p4mcIArollN2co5sdZr-FFUE8bksfMIRzk",
                        "name": "Iphone 11 128gb"
                    },
                    {
                        "review_count": "",
                        "review_rating": "",
                        "seller_url": "https://shop.halebop.se/mobiltelefoner/apple/mycket-bra-skick-iphone-11-64gb-svart/121371",
                        "seller": "Halebop - TextAds",
                        "condition": "Begagnad",
                        "shipping": 0,
                        "currency": "SEK",
                        "price": 399,
                        "url": "https://shop.halebop.se/mobiltelefoner/apple/mycket-bra-skick-iphone-11-64gb-svart/121371",
                        "name": "iPhone 11 64GB Svart"
                    },
                    {
                        "review_count": "",
                        "review_rating": "",
                        "seller_url": "https://swappie.com/se/iphone/iphone-11/iphone-11-64gb-lila-4/",
                        "seller": "Swappie",
                        "condition": "Restaurerad",
                        "shipping": 75,
                        "currency": "SEK",
                        "price": 3469,
                        "url": "https://swappie.com/se/iphone/iphone-11/iphone-11-64gb-lila-4/",
                        "name": "Apple iPhone 11 64GB Lila Apple"
                    },
                    {
                        "review_count": "",
                        "review_rating": "",
                        "seller_url": "https://cdon.se/hemelektronik/apple-iphone-11-64gb-svart-p110205808",
                        "seller": "cdon.se",
                        "condition": "",
                        "shipping": 29,
                        "currency": "SEK",
                        "price": 6990,
                        "url": "https://cdon.se/hemelektronik/apple-iphone-11-64gb-svart-p110205808",
                        "name": "Apple iPhone 11 64GB – Svart - Mobiltelefoner"
                    },
                    {
                        "review_count": 45049,
                        "review_rating": 4.6,
                        "seller_url": "https://telestore.se/kop-mobil/iphone/iphone-11/64gb-utmarkt-85-iphone-11-green/?srsltid=AYJSbAcEH3d_86p_BnrEYbc2__b0W1AIIgTP1j7VBeHXNAddMu_-NlSzRvI",
                        "seller": "Telestore.se",
                        "condition": "Restaurerad",
                        "shipping": 49,
                        "currency": "SEK",
                        "price": 4299,
                        "url": "https://www.google.se/shopping/product/r/SE/8975469375232129950?prds=oid:6609143757138053169,eto:6609143757138053169_0,epd:6609143757138053169,prmr:1,rsk:PC_8023149794696260886&q=iphone+11&rss=ChZQQ184MDIzMTQ5Nzk0Njk2MjYwODg2&hl=sv&gl=se",
                        "name": "Apple iPhone 11 64 GB Grön Gratis"
                    },
                    {
                        "review_count": 17002,
                        "review_rating": 4.6,
                        "seller_url": "https://www.mediamarkt.se/sv/product/_apple-iphone-12-5g-64gb-6-1-smartphone-vit-1329678.html?utm_source=google&utm_medium=seo-product%20feed",
                        "seller": "MediaMarkt.se",
                        "condition": "",
                        "shipping": 0,
                        "currency": "SEK",
                        "price": 8290,
                        "url": "https://www.google.se/shopping/product/r/SE/4832077415325889457?prds=oid:13449489965197928376,eto:13449489965197928376_0,epd:13449489965197928376,prmr:1,rsk:PC_14074616196041694734&q=iphone+11&rss=ChdQQ18xNDA3NDYxNjE5NjA0MTY5NDczNA%3D%3D&hl=sv&gl=se",
                        "name": ". iPhone 12 64GB Vit"
                    },
                    {
                        "review_count": "",
                        "review_rating": "",
                        "seller_url": "https://www.alina.se/Produkt.aspx?site=Test&T2=IP11_BACK_YL",
                        "seller": "Alina.se",
                        "condition": "",
                        "shipping": 49,
                        "currency": "SEK",
                        "price": 1999,
                        "url": "https://www.alina.se/Produkt.aspx?site=Test&T2=IP11_BACK_YL",
                        "name": "Apple iPhone 11 - Baksidebyte Org - Yellow"
                    },
                    {
                        "review_count": 44622,
                        "review_rating": 4.6,
                        "seller_url": "https://www.gotlaptopparts.com/products/apple-iphone-11-a2111-6-1-smartphone-64gb-sprint-only-purple-mwk52ll-a-83?variant=43235693330654&currency=USD&utm_medium=product_sync&utm_source=google&utm_content=sag_organic&utm_campaign=sag_organic&srsltid=AYJSbAfMU3w8S6t0pUF2My_ID2smZ36ef5CwzF1dwiFnUfI_hF-JQcGE4aQ",
                        "seller": "gotlaptopparts.com",
                        "condition": "",
                        "shipping": 1450.08,
                        "currency": "SEK",
                        "price": 3648.87,
                        "url": "https://www.google.se/shopping/product/r/SE/14366534205120661389?prds=oid:12499461307571075068,eto:12499461307571075068_0,epd:12499461307571075068,prmr:1,rsk:PC_8023149794696260886&q=iphone+11&rss=ChZQQ184MDIzMTQ5Nzk0Njk2MjYwODg2&hl=sv&gl=se",
                        "name": "Apple iPhone 11 - 4G Smartphone - Dual-SIM / Internal Memory 64 GB - LCD Display - 6.1 inch - 1792 x 828 Pixels - 2x Rear Cameras 12 MP, 12 Mp - Front"
                    },
                    {
                        "review_count": 44622,
                        "review_rating": 4.6,
                        "seller_url": "https://www.refurbed.se/p/iphone-11/4793/?co=se&utm_cluster=gradeA&utm_content=iphone-11-4793&utm_group=iphone-11",
                        "seller": "refurbed.se",
                        "condition": "Restaurerad",
                        "shipping": 0,
                        "currency": "SEK",
                        "price": 6146.88,
                        "url": "https://www.google.se/shopping/product/r/SE/6872241940907198451?prds=oid:10618610593107152761,eto:10618610593107152761_0,epd:10618610593107152761,prmr:1,rsk:PC_8023149794696260886&q=iphone+11&rss=ChZQQ184MDIzMTQ5Nzk0Njk2MjYwODg2&hl=sv&gl=se",
                        "name": "iPhone 11 - 256GB - Gul"
                    },
                    {
                        "review_count": "",
                        "review_rating": "",
                        "seller_url": "https://www.komplettforetag.se/product/1173213/apple/iphone/iphone/iphone-11-64gb-svart?ChooseSegment=1&srsltid=AYJSbAfdcg0Ur3OpmNIsqorOYWZVGFf-vw0OkF8wqLx79h8ueSJKHZEwTQM",
                        "seller": "Komplett Företag",
                        "condition": "",
                        "shipping": 59,
                        "currency": "SEK",
                        "price": 5790,
                        "url": "https://www.komplettforetag.se/product/1173213/apple/iphone/iphone/iphone-11-64gb-svart?ChooseSegment=1&srsltid=AYJSbAfdcg0Ur3OpmNIsqorOYWZVGFf-vw0OkF8wqLx79h8ueSJKHZEwTQM",
                        "name": "iPhone 11 64GB (svart)"
                    },
                    {
                        "review_count": 44622,
                        "review_rating": 4.6,
                        "seller_url": "https://www.tradeinn.com/techinn/en/apple-iphone-11-64gb-6.1/137821900/p?utm_source=google_products&utm_medium=merchant&id_producte=11865387&country=se",
                        "seller": "Techinn.com",
                        "condition": "",
                        "shipping": 96.99,
                        "currency": "SEK",
                        "price": 5956.99,
                        "url": "https://www.google.se/shopping/product/r/SE/17842000668670187832?prds=oid:2454076103308587249,eto:2454076103308587249_0,epd:2454076103308587249,prmr:1,rsk:PC_8023149794696260886&q=iphone+11&rss=ChZQQ184MDIzMTQ5Nzk0Njk2MjYwODg2&hl=sv&gl=se",
                        "name": "Apple Iphone 11 64gb 6.1 White"
                    },
                    {
                        "review_count": 44622,
                        "review_rating": 4.6,
                        "seller_url": "https://www.certideal.se/iphone-11-rekonditionerad/iphone-11-256-gb-svart-5994?srsltid=AYJSbAd7zRVHn552LPXPRn4LIUkoEt_SDaRFQorH22xPGr-hYpixeQBflno",
                        "seller": "CertiDeal.se",
                        "condition": "Restaurerad",
                        "shipping": 25,
                        "currency": "SEK",
                        "price": 4945,
                        "url": "https://www.google.se/shopping/product/r/SE/10507739572629035335?prds=oid:16775285869308969893,eto:16775285869308969893_0,epd:16775285869308969893,prmr:1,rsk:PC_8023149794696260886&q=iphone+11&rss=ChZQQ184MDIzMTQ5Nzk0Njk2MjYwODg2&hl=sv&gl=se",
                        "name": "Apple iPhone 11 256 GB Svart upplåst"
                    },
                    {
                        "review_count": 500,
                        "review_rating": 4.4,
                        "seller_url": "https://www.apple.com/se/shop/go/product/MX0H2?cid=aos-se-seo-pla",
                        "seller": "Apple",
                        "condition": "",
                        "shipping": 0,
                        "currency": "SEK",
                        "price": 495,
                        "url": "https://www.google.se/shopping/product/r/SE/2369488235728547602?prds=oid:1439088600759390131,eto:1439088600759390131_0,epd:1439088600759390131,prmr:1,rsk:PC_5444876497486124077&q=iphone+11&rss=ChZQQ181NDQ0ODc2NDk3NDg2MTI0MDc3&hl=sv&gl=se",
                        "name": "Apple Case Iphone 11 Pro Max Transparent"
                    },
                    {
                        "review_count": 3,
                        "review_rating": 4.7,
                        "seller_url": "https://www.ebay.com/itm/324879899612?var=513922716703",
                        "seller": "eBay",
                        "condition": "",
                        "shipping": 0,
                        "currency": "SEK",
                        "price": 5205.15,
                        "url": "https://www.ebay.com/itm/324879899612?var=513922716703",
                        "name": "Apple Iphone 11 Pro 64gb 256gb 512gb (unlocked) 1 Year"
                    },
                    {
                        "review_count": 2878,
                        "review_rating": 4.6,
                        "seller_url": "https://www.elgiganten.se/product/mobiler-tablets-smartklockor/mobiltelefon/iphone-13-mini-5g-smartphone-128gb-midnight/361902",
                        "seller": "Elgiganten Sverige",
                        "condition": "",
                        "shipping": 0,
                        "currency": "SEK",
                        "price": 8690,
                        "url": "https://www.google.se/shopping/product/r/SE/9595685719329929779?prds=oid:17038588127108690865,eto:17038588127108690865_0,epd:17038588127108690865,prmr:1,rsk:PC_1686283355608115465&q=iphone+11&rss=ChZQQ18xNjg2MjgzMzU1NjA4MTE1NDY1&hl=sv&gl=se",
                        "name": "Iphone 13 mini 128gb"
                    },
                    {
                        "review_count": "",
                        "review_rating": "",
                        "seller_url": "https://netzone.se/begagnad-iphone/iphone-11-pro/iphone-11-pro-64gb-rymdgra-3?twsCurrency=SEK&srsltid=AYJSbAenW7gyrvBf2F3ZVSpKHdbQJBZwANp3W3mPlJsFVb_hGG8VRNgnxa4",
                        "seller": "Netzone.se",
                        "condition": "Begagnad",
                        "shipping": 79,
                        "currency": "SEK",
                        "price": 5490,
                        "url": "https://netzone.se/begagnad-iphone/iphone-11-pro/iphone-11-pro-64gb-rymdgra-3?twsCurrency=SEK&srsltid=AYJSbAenW7gyrvBf2F3ZVSpKHdbQJBZwANp3W3mPlJsFVb_hGG8VRNgnxa4",
                        "name": "iPhone 11 Pro 64GB Rymdgrå - Skick B"
                    },
                    {
                        "review_count": "",
                        "review_rating": "",
                        "seller_url": "https://www.alina.se/Produkt.aspx?site=Test&T2=IP11_BACK_RD",
                        "seller": "Alina.se",
                        "condition": "",
                        "shipping": 49,
                        "currency": "SEK",
                        "price": 1999,
                        "url": "https://www.alina.se/Produkt.aspx?site=Test&T2=IP11_BACK_RD",
                        "name": "Apple iPhone 11 - Baksidebyte Org - Red"
                    },
                    {
                        "review_count": 6696,
                        "review_rating": 4.6,
                        "seller_url": "https://shop.halebop.se/mobiltelefoner/apple/nyskick-11-pro-256gb-guld/117738",
                        "seller": "Halebop",
                        "condition": "Begagnad",
                        "shipping": 0,
                        "currency": "SEK",
                        "price": 419,
                        "url": "https://www.google.se/shopping/product/r/SE/5235023816292609232?prds=oid:17852549403634477252,eto:17852549403634477252_0,epd:17852549403634477252,prmr:1,rsk:PC_4343141063645219104&q=iphone+11&rss=ChZQQ180MzQzMTQxMDYzNjQ1MjE5MTA0&hl=sv&gl=se",
                        "name": "Iphone 11 Pro 256gb"
                    },
                    {
                        "review_count": 44622,
                        "review_rating": 4.6,
                        "seller_url": "https://www.computersalg.se/i/5866720/apple-iphone-11-4g-smartphone-dual-sim-internal-memory-128-gb-lcd-sk%C3%A4rm-6-1-1792-x-828-pixlar-2-bakre-kameror-12-mp-12-mp",
                        "seller": "ComputerSalg.se",
                        "condition": "",
                        "shipping": 0,
                        "currency": "SEK",
                        "price": 7687,
                        "url": "https://www.google.se/shopping/product/r/SE/12600623597605938023?prds=oid:10851938225365763720,eto:10851938225365763720_0,epd:10851938225365763720,prmr:1,rsk:PC_8023149794696260886&q=iphone+11&rss=ChZQQ184MDIzMTQ5Nzk0Njk2MjYwODg2&hl=sv&gl=se",
                        "name": "MOBILE PHONE IPHONE 11/128GB Black MWM02 APPLE"
                    },
                    {
                        "review_count": "",
                        "review_rating": "",
                        "seller_url": "https://telefy.se/produkt/begagnad-mobil/iphone-11-64gb-svart-klass-b-vmb/",
                        "seller": "Telefy.se",
                        "condition": "",
                        "shipping": 79,
                        "currency": "SEK",
                        "price": 4299,
                        "url": "https://telefy.se/produkt/begagnad-mobil/iphone-11-64gb-svart-klass-b-vmb/",
                        "name": "iPhone 11 - 64GB - Svart - Klass B (VMB)"
                    },
                    {
                        "review_count": "",
                        "review_rating": "",
                        "seller_url": "https://www.tradera.com/item/340186/559239784/apple-iphone-11-64gb-yellow-som-ny",
                        "seller": "Tradera",
                        "condition": "Begagnad",
                        "shipping": 0,
                        "currency": "SEK",
                        "price": 4649,
                        "url": "https://www.tradera.com/item/340186/559239784/apple-iphone-11-64gb-yellow-som-ny",
                        "name": "Apple iPhone 11 64GB Yellow - Som ny"
                    },
                    {
                        "review_count": "",
                        "review_rating": "",
                        "seller_url": "https://www.backmarket.se/sv-se/p/iphone-11-pro-64-gb-gra-utrymme-olast/8a9d4ab9-46f9-406b-8a10-c18a719cda81?shopping=gmc&srsltid=AYJSbAdQZCmIl_sRtCsrAnWVaXsmiH2B5dBr7mP9gBlJC7KfsdLuy_arWqM#?l=11",
                        "seller": "Back Market",
                        "condition": "Restaurerad",
                        "shipping": 0,
                        "currency": "SEK",
                        "price": 5196.04,
                        "url": "https://www.backmarket.se/sv-se/p/iphone-11-pro-64-gb-gra-utrymme-olast/8a9d4ab9-46f9-406b-8a10-c18a719cda81?shopping=gmc&srsltid=AYJSbAdQZCmIl_sRtCsrAnWVaXsmiH2B5dBr7mP9gBlJC7KfsdLuy_arWqM#?l=11",
                        "name": "Apple iPhone 11 Pro 64GB - Grå Utrymme - Rekonditionerad"
                    },
                    {
                        "review_count": 656,
                        "review_rating": 4.5,
                        "seller_url": "https://www.jollymobile.com/shop/iphone-11-skal-vaeskor/25076-apple-silikon-skal-till-iphone-11-mwvu2zma-svart-190199269057.html",
                        "seller": "Jolly Mobile",
                        "condition": "",
                        "shipping": 29,
                        "currency": "SEK",
                        "price": 375,
                        "url": "https://www.google.se/shopping/product/r/SE/11824358818079410558?prds=oid:14301246418054998599,eto:14301246418054998599_0,epd:14301246418054998599,prmr:1,rsk:PC_2728675132695830343&q=iphone+11&rss=ChZQQ18yNzI4Njc1MTMyNjk1ODMwMzQz&hl=sv&gl=se",
                        "name": "APPLE SILIKONSKAL IPHONE 11 SVART"
                    },
                    {
                        "review_count": 12046,
                        "review_rating": 4.6,
                        "seller_url": "https://www.dustinhome.se/product/5011280618/iphone-13?ssel=true&srsltid=AYJSbAeFWjxIeg9NhU-CMRyHiBiZ8zW1Z_KfV2CaKRglwaHWJrRt7SruK_E",
                        "seller": "Dustin Home SE",
                        "condition": "",
                        "shipping": 0,
                        "currency": "SEK",
                        "price": 10569,
                        "url": "https://www.google.se/shopping/product/r/SE/7732539528939207054?prds=oid:5470313518516022273,eto:5470313518516022273_0,epd:5470313518516022273,prmr:1,rsk:PC_8971650804785857268&q=iphone+11&rss=ChZQQ184OTcxNjUwODA0Nzg1ODU3MjY4&hl=sv&gl=se",
                        "name": "Iphone 13 128gb"
                    },
                    {
                        "review_count": "",
                        "review_rating": "",
                        "seller_url": "https://shop.halebop.se/mobiltelefoner/apple/mycket-bra-skick-11-pro-64gb-midnattsgron/117693",
                        "seller": "Halebop - TextAds",
                        "condition": "Begagnad",
                        "shipping": 0,
                        "currency": "SEK",
                        "price": 449,
                        "url": "https://shop.halebop.se/mobiltelefoner/apple/mycket-bra-skick-11-pro-64gb-midnattsgron/117693",
                        "name": "iPhone 11 Pro 64GB Midnattsgr?n"
                    },
                    {
                        "review_count": 44622,
                        "review_rating": 4.6,
                        "seller_url": "https://www.ebay.com/itm/403890096597",
                        "seller": "eBay",
                        "condition": "",
                        "shipping": 0,
                        "currency": "SEK",
                        "price": 8335.34,
                        "url": "https://www.google.se/shopping/product/r/SE/1112937734248658671?prds=oid:14205512654248137827,eto:14205512654248137827_0,epd:14205512654248137827,prmr:1,rsk:PC_8023149794696260886&q=iphone+11&rss=ChZQQ184MDIzMTQ5Nzk0Njk2MjYwODg2&hl=sv&gl=se",
                        "name": "iPhone 11 128GB Black"
                    },
                    {
                        "review_count": 57,
                        "review_rating": 4.7,
                        "seller_url": "https://www.comviq.se/mobiler/apple-iphone-13-mini",
                        "seller": "Comviq",
                        "condition": "",
                        "shipping": 0,
                        "currency": "SEK",
                        "price": "0 kr nu+399 kr i 36 månader",
                        "url": "https://www.google.se/shopping/product/r/SE/10654867731055396935?prds=oid:13490959192124966564,eto:13490959192124966564_0,epd:13490959192124966564,prmr:1,rsk:PC_16825921221298407573&q=iphone+11&rss=ChdQQ18xNjgyNTkyMTIyMTI5ODQwNzU3Mw%3D%3D&hl=sv&gl=se",
                        "name": "APPLE IPHONE 13 MINI 128 GB GRÖN"
                    },
                    {
                        "review_count": "",
                        "review_rating": "",
                        "seller_url": "https://merateknik.se/begagnade-mobiler/iphone/iphone-11-12/apple-iphone-11-64gb-rod-beg-okej-skick-olst",
                        "seller": "merateknik.se",
                        "condition": "",
                        "shipping": 0,
                        "currency": "SEK",
                        "price": 3490,
                        "url": "https://merateknik.se/begagnade-mobiler/iphone/iphone-11-12/apple-iphone-11-64gb-rod-beg-okej-skick-olst",
                        "name": "Apple iPhone 11 64GB Röd - BEG - OKEJ SKICK - OLÅST"
                    },
                    {
                        "review_count": "",
                        "review_rating": "",
                        "seller_url": "https://www.certideal.se/iphone-11-rekonditionerad/iphone-11-64-gb-vit-4933?srsltid=AYJSbAe2HSn72QiKjWAGy9dKHCjn_qdZVl_t194CTrR4NVRatFoW0GtfGrw",
                        "seller": "CertiDeal.se",
                        "condition": "Restaurerad",
                        "shipping": 25,
                        "currency": "SEK",
                        "price": 4062,
                        "url": "https://www.certideal.se/iphone-11-rekonditionerad/iphone-11-64-gb-vit-4933?srsltid=AYJSbAe2HSn72QiKjWAGy9dKHCjn_qdZVl_t194CTrR4NVRatFoW0GtfGrw",
                        "name": "iPhone 11 64 Gb Vit - 24 Månaders Garanti - Shipping 4 Dagar - Nöjd Eller Pengarna Tillbaka - CertiDeal"
                    },
                    {
                        "review_count": "",
                        "review_rating": "",
                        "seller_url": "https://www.alina.se/Produkt.aspx?site=Test&T2=IP11_BACK_WH",
                        "seller": "Alina.se",
                        "condition": "",
                        "shipping": 49,
                        "currency": "SEK",
                        "price": 1999,
                        "url": "https://www.alina.se/Produkt.aspx?site=Test&T2=IP11_BACK_WH",
                        "name": "Apple iPhone 11 - Baksidebyte Org - White"
                    },
                    {
                        "review_count": "",
                        "review_rating": "",
                        "seller_url": "https://swappie.com/se/iphone/iphone-11/iphone-11-64gb-vit-2/",
                        "seller": "Swappie",
                        "condition": "Restaurerad",
                        "shipping": 75,
                        "currency": "SEK",
                        "price": 4989,
                        "url": "https://swappie.com/se/iphone/iphone-11/iphone-11-64gb-vit-2/",
                        "name": "Apple iPhone 11 64GB Vit Apple"
                    },
                    {
                        "review_count": "",
                        "review_rating": "",
                        "seller_url": "https://www.proshop.se/Mobile/Apple-iPhone-11-64GB-Black/2799917?utm_source=google&utm_medium=cpc&utm_campaign=searchengine&srsltid=AYJSbAeM7bYDjSDwE50o56WhucTaNiEK3waTu-jnSkvtYgBoza2-hkj7Qaw",
                        "seller": "Proshop.se",
                        "condition": "",
                        "shipping": 0,
                        "currency": "SEK",
                        "price": 7290,
                        "url": "https://www.proshop.se/Mobile/Apple-iPhone-11-64GB-Black/2799917?utm_source=google&utm_medium=cpc&utm_campaign=searchengine&srsltid=AYJSbAeM7bYDjSDwE50o56WhucTaNiEK3waTu-jnSkvtYgBoza2-hkj7Qaw",
                        "name": "Apple iPhone 11 64GB - Black,Mobile"
                    },
                    {
                        "review_count": "",
                        "review_rating": "",
                        "seller_url": "https://www.backmarket.se/sv-se/p/iphone-11-64-gb-svart-olast/0106bb6f-3975-4794-b9a0-7d920669484c?shopping=gmc&srsltid=AYJSbAccC9Gm8WIBE-cakj9Iq0J2wkHG-16w5RF9sJuVvMGRQIcVJulIO0Q#?l=11",
                        "seller": "Back Market",
                        "condition": "Restaurerad",
                        "shipping": 0,
                        "currency": "SEK",
                        "price": 5436.1,
                        "url": "https://www.backmarket.se/sv-se/p/iphone-11-64-gb-svart-olast/0106bb6f-3975-4794-b9a0-7d920669484c?shopping=gmc&srsltid=AYJSbAccC9Gm8WIBE-cakj9Iq0J2wkHG-16w5RF9sJuVvMGRQIcVJulIO0Q#?l=11",
                        "name": "Apple iPhone 11 64GB - Svart - Rekonditionerad"
                    },
                    {
                        "review_count": "",
                        "review_rating": "",
                        "seller_url": "https://fyndiq.se/produkt/iphone-11-yellow-128-gb-klass-a-refurbished-f210b5d152d04795/?srsltid=AYJSbAexo3uqokxeLO3dZr75WR9UYiMeHD9e6JEAtgYnX-GSCNEqfVvBgxY",
                        "seller": "Fyndiq.se",
                        "condition": "Restaurerad",
                        "shipping": 0,
                        "currency": "SEK",
                        "price": 5249,
                        "url": "https://fyndiq.se/produkt/iphone-11-yellow-128-gb-klass-a-refurbished-f210b5d152d04795/?srsltid=AYJSbAexo3uqokxeLO3dZr75WR9UYiMeHD9e6JEAtgYnX-GSCNEqfVvBgxY",
                        "name": "Iphone 11 Yellow 128 Gb Klass A (refurbished)"
                    },
                    {
                        "review_count": "",
                        "review_rating": "",
                        "seller_url": "https://www.telefonshoppen.se/mobiltelefoner/iphone-11-64gb-1?att=V2hpdGU=",
                        "seller": "Telefonshoppen",
                        "condition": "",
                        "shipping": 0,
                        "currency": "SEK",
                        "price": 6470,
                        "url": "https://www.telefonshoppen.se/mobiltelefoner/iphone-11-64gb-1?att=V2hpdGU=",
                        "name": "iPhone 11 64GB | White"
                    },
                    {
                        "review_count": "",
                        "review_rating": "",
                        "seller_url": "https://www.hallon.se/foretag/mobiler/iphone-12-128gb",
                        "seller": "Hallon",
                        "condition": "",
                        "shipping": 0,
                        "currency": "SEK",
                        "price": 360,
                        "url": "https://www.hallon.se/foretag/mobiler/iphone-12-128gb",
                        "name": "iPhone 12 128GB med mobilabonnemang. Jobbmobil från hallon. Välkomna till hallon företag!"
                    },
                    {
                        "review_count": "",
                        "review_rating": "",
                        "seller_url": "https://soldfy.se/iphone-11-baksida-med-smadelar-original-pulled-gron?srsltid=AYJSbAeCV45kmlApxPqDn2iX-DVnUH0kP25P75jGShdQV4m6I6w_SFBOZkY",
                        "seller": "Soldfy.se",
                        "condition": "",
                        "shipping": 19,
                        "currency": "SEK",
                        "price": 1399,
                        "url": "https://www.google.se/shopping/product/r/SE/3226493265616550617?prds=oid:9900817412253543105,eto:9900817412253543105_0,epd:9900817412253543105,prmr:1&q=iphone+11&hl=sv&gl=se",
                        "name": "Iphone 11 Baksida Komplett Med Smådelar - Grön"
                    },
                    {
                        "review_count": 31,
                        "review_rating": 4.7,
                        "seller_url": "https://www.datagrottan.se/apple-folio-vikbart-fodral-foer/cat-p/c/p1000420142",
                        "seller": "Datagrottan",
                        "condition": "",
                        "shipping": 49,
                        "currency": "SEK",
                        "price": 2176,
                        "url": "https://www.google.se/shopping/product/r/SE/17694111448734141775?prds=oid:9317739954510768185,eto:9317739954510768185_0,epd:9317739954510768185,prmr:1,rsk:CID_17694111448734141775&q=iphone+11&rss=ChhDSURfMTc2OTQxMTE0NDg3MzQxNDE3NzU%3D&hl=sv&gl=se",
                        "name": "Apple Folio Iphone 11 Pro Max Aubergine"
                    },
                    {
                        "review_count": "",
                        "review_rating": "",
                        "seller_url": "https://www.tre.se/treforetag/handla/mobiltelefoner/apple/iphone-11?articleId=G0YEDwafAP_VBEE0I9dYnQ%3D%3D&pricePlanId=7WSlO-e80u22yHFtivNYJA%3D%3D",
                        "seller": "tre.se",
                        "condition": "",
                        "shipping": 0,
                        "currency": "SEK",
                        "price": "0 kr nu+449 kr i 24 månader",
                        "url": "https://www.tre.se/treforetag/handla/mobiltelefoner/apple/iphone-11?articleId=G0YEDwafAP_VBEE0I9dYnQ%3D%3D&pricePlanId=7WSlO-e80u22yHFtivNYJA%3D%3D",
                        "name": "Apple iPhone 11 64GB med abonnemang 3Företag inkl. 3Världen"
                    },
                    {
                        "review_count": "",
                        "review_rating": "",
                        "seller_url": "https://ixpress.se/begagnad-iphone-11-64gb-vit-grade-a?srsltid=AYJSbActF1Iot21Ras4QW8cdamHghDee5F9dVjNm3aTteAechtdNnYqbsSA",
                        "seller": "iXpress.se",
                        "condition": "Restaurerad",
                        "shipping": 79,
                        "currency": "SEK",
                        "price": 4399,
                        "url": "https://ixpress.se/begagnad-iphone-11-64gb-vit-grade-a?srsltid=AYJSbActF1Iot21Ras4QW8cdamHghDee5F9dVjNm3aTteAechtdNnYqbsSA",
                        "name": "Begagnad iPhone 11 64GB Vit Grade A"
                    },
                    {
                        "review_count": "",
                        "review_rating": "",
                        "seller_url": "https://shop.halebop.se/mobiltelefoner/apple/nyskick-11-pro-64gb-rymdgra-nyskick/117600",
                        "seller": "Halebop - TextAds",
                        "condition": "Begagnad",
                        "shipping": 0,
                        "currency": "SEK",
                        "price": 519,
                        "url": "https://shop.halebop.se/mobiltelefoner/apple/nyskick-11-pro-64gb-rymdgra-nyskick/117600",
                        "name": "iPhone 11 Pro 64GB Rymdgr?"
                    },
                    {
                        "review_count": "",
                        "review_rating": "",
                        "seller_url": "https://primemobile.se/iphone-11-pro-max-skarmbyte-36.html",
                        "seller": "primemobile.se",
                        "condition": "",
                        "shipping": 99,
                        "currency": "SEK",
                        "price": 2000,
                        "url": "https://primemobile.se/iphone-11-pro-max-skarmbyte-36.html",
                        "name": "iPhone 11 Byta Backstycke"
                    },
                    {
                        "review_count": "",
                        "review_rating": "",
                        "seller_url": "https://cdon.se/hemelektronik/apple-iphone-11-128gb-svart-utan-headset-p92781912",
                        "seller": "cdon.se",
                        "condition": "",
                        "shipping": 0,
                        "currency": "SEK",
                        "price": 7364,
                        "url": "https://cdon.se/hemelektronik/apple-iphone-11-128gb-svart-utan-headset-p92781912",
                        "name": "APPLE iPhone 11 128GB Svart - utan headset - Mobiltelefoner"
                    },
                    {
                        "review_count": "",
                        "review_rating": "",
                        "seller_url": "https://www.ebay.com/itm/224497871184",
                        "seller": "eBay",
                        "condition": "",
                        "shipping": 0,
                        "currency": "SEK",
                        "price": 4579.22,
                        "url": "https://www.ebay.com/itm/224497871184",
                        "name": "Apple Iphone 11 - 64gb (factory Unlocked) Black Apple Warranty"
                    }
                ],
                "offers_count": 60
            },
            "success": true
        }
    ]
}]

export default productConst;
